app/models/task.py
import datetime
import itertools
from enum import Enum

from mongoengine import signals

from .. import db
from .user import User
from .utils import handler


@handler(signals.pre_save)
def update_modified(sender, document):
    document.update_at = datetime.datetime.utcnow()


class Category(Enum):
    SHORT_TERM = 'short_term'
    LONG_TERM = 'long_term'
    FLIP = 'flip'


class UserTag(Enum):
    impressive = 'impressive'
    reviewed = 'reviewed'
    to_do = 'to do'
    cache = 'cache'


class SystemTag(Enum):
    cached = 'cached'
    unable_to_cache = 'unable to cache'


class DocumentCache(db.EmbeddedDocument):  # type: ignore
    content = db.StringField()
    update_at = db.DateTimeField(default=datetime.datetime.utcnow)


@update_modified.apply
class DocumentMeta(db.DynamicDocument):  # type: ignore
    theme = db.StringField(max_length=256, required=True, unique=True)
    category = db.StringField(
        max_length=64,
        required=True,
        choices=[category.value for category in Category])
    url = db.StringField(max_length=1024)
    priority = db.IntField()
    comment = db.ListField(db.StringField())
    tags = db.ListField(
        db.StringField(choices=[
            tag.value
            for tag in iter(itertools.chain(UserTag, SystemTag))  # type:ignore
        ]))
    update_at = db.DateTimeField(default=datetime.datetime.utcnow)
    create_by = db.ReferenceField(User)
    cache = db.EmbeddedDocumentField(DocumentCache)
    meta = {
        'collection': 'document_meta',
        'indexes': [{
            'fields': ['theme']
        }, {
            'fields': ['category']
        }, {
            'fields': ['$theme', "$comment", "$cache.content"],
            'default_language': 'english',
            'weights': {
                'theme': 8,
                'comment': 5,
                'cache.content': 3
            }
        }]
    }  # yapf: disable

    def is_review_done(self):
        return UserTag.reviewed.value in self.tags

    @classmethod
    def pre_save(cls, sender, document, **kwargs):
        if document.is_review_done():
            document.priority = 0

    def __repr__(self):
        return f'<Document \'{str(self)}\'>'

    def __str__(self):
        if len(self.theme) > 30:
            title = f'{self.theme[:30]}...'
        else:
            title = self.theme
        return title


signals.pre_save.connect(DocumentMeta.pre_save, sender=DocumentMeta)

app/task/forms.py
from flask_wtf import FlaskForm
from mongoengine import Q
from wtforms import (HiddenField, SelectField, SelectMultipleField,
                     StringField, SubmitField)
from wtforms.fields.html5 import URLField
from wtforms.validators import URL, InputRequired, Length, ValidationError

from app.globals import INVALID_OBJECT_ID
from app.models import Category, DocumentMeta, SystemTag, UserTag, itertools
from app.utils import beautify_static


class DocMetaForm(FlaskForm):
    id = HiddenField('Id')
    theme = StringField('Theme', validators=[InputRequired(), Length(1, 256)])
    category = SelectField(
        'Category',
        validators=[InputRequired()],
        choices=[(cat.value, cat.value.lower()) for cat in Category])
    url = URLField(
        'Link', validators=[InputRequired(),
                            Length(1, 1024),
                            URL()])
    tags = SelectMultipleField(
        'Tags',
        choices=[
            (tag.value, beautify_static(tag.value))  # type:ignore
            for tag in iter(itertools.chain(UserTag, SystemTag))  # type:ignore
        ])
    priority = SelectField(
        'Priority',
        choices=[(i, i) for i in range(0, 4)],
        coerce=int,
        default=0)
    submit = SubmitField('Submit Document')

    def validate_theme(self, theme):
        if DocumentMeta.objects(
                Q(theme=theme.data) & Q(
                    id__ne=self.id.data or INVALID_OBJECT_ID)).first():
            raise ValidationError('Theme already exists.')

app/task/__init__.py
from app.task.views import task

app/task/views.py
from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   url_for)
from flask_login import current_user, login_required
from flask_mongoengine.pagination import Pagination
from mongoengine.errors import NotUniqueError

from app.globals import ALL_CATEGORY, DOCUMENT_PER_PAGE
from app.models import Category, DocumentMeta, Permission
from app.task.forms import DocMetaForm
from app.task.utils import MY_DOC_PIPELINE

task = Blueprint('task', __name__)


@task.route('/doc_meta/my_documents')
@login_required
def my_doc_meta():
    """Get all documents meta data of user"""
    page = request.args.get('page', 1, type=int)
    category = request.args.get(
        'category', Category.SHORT_TERM.value, type=str)
    search = request.args.get('search', None)
    filter = {'create_by': current_user.id}

    if category != ALL_CATEGORY:
        filter['category'] = category

    documents = DocumentMeta.objects(**filter).exclude('cache')

    if search:
        documents = documents.search_text(search)
        documents = documents.order_by('$text_score')
    else:
        documents = list(documents.aggregate(*MY_DOC_PIPELINE))
    documents = Pagination(documents, page=page, per_page=DOCUMENT_PER_PAGE)
    return render_template(
        'task/document_dashboard.html',
        current_category=category,
        current_search=search,
        documents=documents)


@task.route('/doc_meta', methods=['GET', 'POST'])
@login_required
def new_doc_meta():
    """new document meta data for current user"""
    form = DocMetaForm()
    if form.validate_on_submit():
        doc_meta = DocumentMeta(
            theme=form.theme.data,
            category=form.category.data,
            url=form.url.data,
            tags=form.tags.data,
            priority=form.priority.data,
            create_by=current_user.id)
        try:
            doc_meta.save()
        except NotUniqueError:
            flash('Theme already exists.', 'form-error')
        else:
            flash(f'Document {str(doc_meta)} is successfully created.',
                  'form-success')
        return redirect(url_for('task.new_doc_meta'))
    return render_template(
        'task/manage_document.html',
        form=form,
        action='Create',
        data_type='New Document')


@task.route('/doc_meta/<string:doc_meta_id>', methods=['GET', 'POST'])
@login_required
def update_doc_meta(doc_meta_id):
    """update document meta data with given id"""
    doc_meta = DocumentMeta.objects.get_or_404(id=doc_meta_id)
    form = DocMetaForm(obj=doc_meta)
    if form.validate_on_submit():
        try:
            doc_meta.theme = form.theme.data
            doc_meta.category = form.category.data
            doc_meta.url = form.url.data
            doc_meta.tags = form.tags.data
            doc_meta.priority = form.priority.data
            doc_meta.save()
        except NotUniqueError:
            flash('Theme already exists.', 'form-error')
        else:
            flash(f'Document {str(doc_meta)} is successfully updated.',
                  'form-success')
        return redirect(
            url_for('task.update_doc_meta', doc_meta_id=doc_meta_id))
    return render_template(
        'task/manage_document.html',
        form=form,
        action='Update',
        data_type=str(doc_meta))


@task.route('/doc_meta/delete/<string:doc_meta_id>', methods=['GET', 'POST'])
@login_required
def delete_doc_meta(doc_meta_id):
    """delete document meta data with given id"""
    doc_meta = DocumentMeta.objects.get_or_404(id=doc_meta_id)
    if current_user.can(
            Permission.ADMINISTER.value) or current_user == doc_meta.create_by:
        doc_meta.delete()
    else:
        abort(401)
    flash(f'Document {str(doc_meta.theme)} is successfully deleted.',
          'form-success')
    return redirect(url_for('task.my_doc_meta'))


@task.context_processor
def inject_template_global():
    return {
        'categories': [c.value for c in Category],
        'all_category': ALL_CATEGORY
    }

app/templates/task/_document.html
<div class="item">
    <div class="ui middle aligned tiny image">
        <img src="{{ url_for('static', filename='images/task/default_type.png') }}">
    </div>
    <div class="content">
        <div>
            <a class="ui header{% if d.priority == 3 %} red {% elif d.priority == 2 %} blue {% endif %}"
            href="{{ d.url }}" target="_blank">{{ d.theme }}</a>
            <div class="ui right floated">{{ moment(d.update_at).fromNow() }}</div>
        </div>
        <div class="meta">
            <span class="cinema">{{ beautify_static(d.category) }}</span>
        </div>
        <div class="description">
            <div class="ui middle aligned divided list">
                {% for c in d.comment %}
                <div class="item">
                    <div class="content">
                        <span class="header">{{ c }}</span>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="extra">
            <div class="ui basic animated right floated buttons" tabindex="0">
                <div class="ui vertical animated button " tabindex="0">
                    <a class="item" href="{{ url_for('task.update_doc_meta', doc_meta_id= d.id|string) }}">
                        <div class="hidden content">Edit</div>
                        <div class="visible content">
                            <i class="write icon"></i>
                        </div>
                    </a>

                </div>
                <div class="ui vertical animated button" tabindex="0">
                    <a class="item" href="{{ url_for('task.delete_doc_meta', doc_meta_id= d.id|string) }}">
                        <div class="hidden content">Delete</div>
                        <div class="visible content">
                            <i class="trash outline icon"></i>
                        </div>
                    </a>
                </div>
            </div>
            {% for tag in d.tags %}
                <div class="ui label blue">{{ beautify_static(tag) }}</div>
            {% endfor %}
        </div>
    </div>
</div>

app/templates/task/document_dashboard.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'task/task_macros.html' as m %}
{% block content %}
<div class="ui stackable grid container">
    <div class="sixteen wide tablet twelve wide computer centered column">
        <h2 class="ui header">
            <i class="book icon"></i>
            <div class="content">My Documents <div class="sub header">Manage your documents</div></div>
        </h2>

        <div class="ui basic vertical animated right floated button" tabindex="0">
            <a class="item" href="{{ url_for('task.new_doc_meta') }}">
                <div class="hidden content">New</div>
                <div class="visible content">
                    <i class="large plus circle icon"></i>
                </div>
            </a>
        </div>

        <div class="ui menu">
            <div id="select-category" class="ui dropdown item">
                <div class="text">
                    {{ beautify_static(current_category) }}
                </div>
                <i class="dropdown icon"></i>
                <div class="menu">
                    <div class="item" data-value="{{ all_category }}">{{ all_category }}</div>
                    {% for cname in categories %}
                    <div class="item" data-value="{{ cname }}">{{ beautify_static(cname) }}</div>
                    {% endfor %}
                </div>
            </div>
            <div class="ui right search item">
                <div class="ui transparent icon input">
                    <input id="search-doc" type="text" placeholder="Search documents…">
                    <i class="search icon"></i>
                </div>
            </div>
        </div>

        {% set flashes = {
        'error': get_flashed_messages(category_filter=['form-error']),
        'warning': get_flashed_messages(category_filter=['form-check-email']),
        'info': get_flashed_messages(category_filter=['form-info']),
        'success': get_flashed_messages(category_filter=['form-success'])
        } %}
        {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
        {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
        {{ f.form_message(flashes['info'], header='Information', class='info') }}
        {{ f.form_message(flashes['success'], header='Success!', class='success') }}

        <h4 class="ui section divider"></h4>
        <div style="overflow-x: auto;">
            {% if documents.items %}
                <div class="ui divided items">
                    {% for d in documents.items %}
                        {% include 'task/_document.html' %}
                    {% endfor %}
                </div>

                {{ m.render_navigation(documents, 'task.my_doc_meta', current_category, current_search) }}
            {% else %}
                <h1  class="ui disabled header centered">No Document Found</h1 >
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#search-doc').keypress(function (event) {
                if(event.keyCode != "13") return;
                var searchText = $(this).val();
                window.location.href = "{{ url_for('task.my_doc_meta') }}?category={{ current_category }}&search="+searchText;
            });

            $('#select-category').dropdown({
                onChange: function (value, text, $selectedItem) {
                    window.location.href = "{{ url_for('task.my_doc_meta') }}?category="+value;
                }
            });
        });
    </script>
{% endblock %}

app/templates/task/manage_document.html
{% extends 'layouts/base.html' %} {% import 'macros/form_macros.html' as f %} {% block content %}
<div class="ui stackable centered grid container">
    <div class="twelve wide column">
        <a class="ui basic compact button" href="{{ url_for('task.my_doc_meta') }}">
            <i class="caret left icon"></i>
            Back to Document List
        </a>
        <h2 class="ui header">
            {{ action }} {{ data_type }}
            {% if action == 'Create' %}
            <div class="sub header">Create a new url based document</div>
            {% elif action == 'Update' %}
            <div class="sub header">Update meta data of the document</div>
            {% endif %}
        </h2>

        {{ f.render_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/task/task_macros.html
{# Macro for creating navigation links #}
{% macro render_navigation(pagination, endpoint, category, search) %}
    <div class="ui pagination menu">
        {% for page in pagination.iter_pages() %}
            {% if page %}
                {% if page != pagination.page %}
                    <a class="item" href="{{ url_for(endpoint, category=category, search=search, page=page) }}">{{ page }}</a>
                {% else %}
                    <a class="active item">{{ page }}</a>
                {% endif %}
            {% else %}
                <span class="disabled item">...</span>
            {% endif %}
        {% endfor %}
    </div>
{% endmacro %}